# **El Sol**
## *Jupyter Notebook version*
###### Important info is in the README:md of the release

### Set Up

In [38]:
# Liberary Imports
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [39]:
# Variables:
# File Paths:
train_path = "./Data/Train Images"
rating_path = "./Data/rating.txt"
run_path = "./Data/Image"

# More Files:
train_full_dir = os.listdir(train_path)
train_dir = []
train_img = []
train_img_rgb = []
train_txt = []
run_full_dir = os.listdir(run_path)
run_dir = []
run_img = []
run_img_rgb = []

### Importing data

#### Importing the images into to the correct format

In [40]:
# Importing the training data

# Adds all files from the trainings-dir into the train_img array and fileters all folders out
for i in train_full_dir:
    sing_train_img_path = os.path.join(train_path, i)
    if os.path.isfile(sing_train_img_path):
        train_dir.append(i)

In [41]:
# Turning the training-img into 500x500 pixel data
for i in train_dir:
    sing_train_img = cv2.imread(os.path.join(train_path, i))
    if sing_train_img is not None:
        train_img.append(cv2.resize(sing_train_img, (500, 500)))

In [42]:
# Turns converts all images from BRG to RGB
for img in train_img:
    train_img_rgb.append(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

In [43]:
# Normalizing the pic from 0-255 to 0.0 to 1.0 and put it into the correct format
train_img = np.array(train_img_rgb) / 255
train_img = train_img.reshape(-1,500*500*3)

#### Importing the answers to the images

In [44]:
# Setting up the text training
with open(rating_path, 'r') as file:
    # Read each line in the file
    for line in file:
        clean_line = line.strip()
        rating = float(clean_line)
        train_txt.append(rating)
train_txt = np.array(train_txt)

#### Importing the images to research

In [45]:
# Adds all files from the Images-dir into the run_img array and fileters all folders out
for i in run_full_dir:
    sing_run_img_path = os.path.join(run_path, i)
    if os.path.isfile(sing_run_img_path):
        run_dir.append(i)

In [46]:
# Turning the training-img into 500x500 pixel data
for i in run_dir:
    sing_run_img = cv2.imread(os.path.join(run_path, i))
    if sing_run_img is not None:
        run_img.append(cv2.resize(sing_run_img, (500, 500)))

In [47]:
for img in run_img:
    run_img_rgb.append(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

In [48]:
run_img = np.array(run_img_rgb) / 255
run_img = run_img.reshape(-1, 500*500*3)

### Building the Model

In [54]:
model = keras.Sequential([
    keras.layers.Dense(256, input_shape=[500*500*3], activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

c:\Users\johan\Code\Python\venv\el-sol\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [50]:
# Compliling and training model
model.compile(optimizer="adam", loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(train_img, train_txt, epochs=50, batch_size=32)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.7500 - loss: 0.9946
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 471ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 469ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 456ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 455ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 459ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 482ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 477ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 469ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 462ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 483ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 

In [51]:
model_loss, model_acc = model.evaluate(train_img, train_txt, verbose=1)
print(f"The Model is {int(model_acc*100)}% accurat")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.0000e+00
The Model is 100% accurat


### Run the model

In [52]:
predictions = model.predict(run_img)
for i in range(len(predictions)):
    print("Image:", run_dir[i])
    print(predictions[i])
    if np.argmax(predictions[i]) == 0:
        print("Output 1")
    elif np.argmax(predictions[i]) == 1:
        print("Output 2")
    elif np.argmax(predictions[i]) == 2:
        print("Output 3 (AI doesnt know)")
    print()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Image: gradient.webp
[1. 0. 0.]
Output 1

Image: test red.webp
[1. 0. 0.]
Output 1

Image: th.webp
[1. 0. 0.]
Output 1

